#!/bin/bash

# quit cmus
# kill the last polybar bar
# TODO: check if it is really the cmus bar
# restore the wallpaper: path to your original wallpaper

feh --bg-fill "$(cat $HOME/.config/wal/last-bg)"

pid=`ps -o pid,args -C "polybar" | grep cmus | cut -d " " -f2`

for p in $pid; do
  polybar-msg -p ${p} cmd quit
done

exit 0
