#!/bin/bash

OFFLINE_STATUS_FILE=$HOME/.config/cmus/scripts/cmus_offline.status

status=$(( ! $(cat "${OFFLINE_STATUS_FILE}") ))

[ $status -eq 0 ] && msg="Auto cover downloading OFF" || msg="Auto cover downloading ON"
notify-send "$msg"

echo $status > "${OFFLINE_STATUS_FILE}"
