#!/bin/bash

# allows to update currently playing track's metadata
# it launch album art retrieval after the update

function parse {
	input=$1
	title=$(echo "$input" | cut -d "|" -f 1)
	artist=$(echo "$input" | cut -d "|" -f 2)
	album=$(echo "$input" | cut -d "|" -f 3)
	track=$(echo "$input" | cut -d "|" -f 4)
  genre=$(echo "$input" | cut -d "|" -f 5)
  year=$(echo "$input" | cut -d "|" -f 6)
}

function print {
	echo "title=$title"
	echo "artist=$artist"
	echo "album=$album"
	echo "track=$track"
	echo "genre=$genre"
	echo "year=$year"
}

function retrieve_tag {
	file="${1}"
	ext=$(ffprobe -hide_banner -loglevel warning -show_format -show_streams -print_format json "$file" |\
	       jq .format.format_name |\
	       tr -d \")
	tags=$(ffprobe -hide_banner -loglevel warning -show_format -show_streams -print_format json "$file")

  echo $ext

	if [ $ext == "ogg" ]; then
	  tags=$(jq -r '.streams[0].tags' <<< $tags)
  else
    tags=$(jq -r '.format.tags' <<< $tags)
  fi

  jq <<< $tags

	title=$(jq -r 'select(.title != null) | .title' <<< "$tags")
	artist=$(jq -r 'select(.artist != null) | .artist' <<< "$tags")
	album=$(jq -r 'select(.album != null) | .album' <<< "$tags")
	track=$(jq -r 'select(.track != null) | .track' <<< "$tags" | cut -d "/" -f1)
  genre=$(jq -r 'select(.genre != null) | .genre' <<< "$tags")
  year=$(jq -r 'select(.year != null) | .year' <<< "$tags")
}

function is_running {
	status=$(cmus-remote --query 2>/dev/null | sed -n 's/^status //p')
	[[ $? -eq 0 && $status == "playing" ]]
}

function err {
	notify-send --urgency="critical" "$1"
	exit 1
}

###############

is_running || err "cmus is not playing any track"

apply_tag="tag"
file=$(cmus-remote --query | sed -n 's/^file //p')

retrieve_tag "$file"

tags=$(
	yad --title "cmus tagger" --form \
		--field=title "$title" \
		--field=artist "$artist" \
		--field=album "$album" \
		--button='Suggest album':"fetch-album \"$artist\" \"$title\"" \
		--field="track number" "$track"  \
		--field=year:NUM "$year" \
		--field=genre "$genre" \
		--button="Submit:0" \
)

[ $? -ne 0 ] && err "form was closed"

parse "$tags"

print

$apply_tag \
	-c						\
	-a "$artist"	\
	-t "$title" 	\
	-A "$album"		\
	-n "$track"		\
	-y "$year"		\
	-g "$genre"		\
	"$file"

[ $? -ne 0 ] && err "error in applying tags"

cmus-remote -C "update-cache"

notify-send "${artist} - ${title}'s tags correctly added"

exit 0
